### ISSUE TITLE
Some questions on model versions and performance

### ISSUE THREAD

**Issue by atiorh** [Roblox/voice-safety-classifier#4]
I enjoyed reading the blog post, kudos to the team! https://research.roblox.com/tech-blog/2024/07/deploying-ml-for-voice-safety

I have two questions:

1-) It looks like this particular model corresponds to the 96M Fine-tuned WavLM. Do you have plans on publishing the Distilled version? Per the blog post, the distilled model adds MFCC pre-processing before the CNN stage so the model can process a shorter sequence. The models without MFCC will need to process a raw waveform of 16,000 kHz * 15 seconds = 240,000 in the CNN layers which adds a lot of compute to the forward pass.

2-) The reported latency numbers are normalized by input audio length but the forward pass FLOPs are not linearly correlated with the input length so it is unclear how fast the system would be for longer inputs from the shared information, e.g. It should be slower than 15 seconds * latency of 1 second input. Are you able to share more insights on this?

<img width="688" alt="Screenshot 2024-07-10 at 11 25 18 AM" src="https://github.com/Roblox/voice-safety-classifier/assets/64497909/6e1ee0ca-4712-4da1-b64c-0119fe3f722c">

**Comment by langma** [comment]
Thanks for your interest! We're happy to see people try out this model 👍 

1) We don't currently have plans on publishing additional versions of this model.

2) You're right, the complexity is not strictly linear. In practice, depending on the hardware, it is close enough though. We encourage you to try out the included [inference code](https://github.com/Roblox/voice-safety-classifier/blob/main/inference.py) and measure your specific use case!
